### Scalars and Vectors

In [1]:
import numpy as np

In [6]:
x1 = np.array([2,3,4])
print(x1)
print(x1.shape)
print(x1[0])

[2 3 4]
(3,)
2


In [10]:
# WE will represent a vector as column vector,that having multiple rows
x = np.array([[2],[4],[6],[9]])
print(x)
print(x.shape)
print(x[0][0])

#convert it into a row vector using reshape operation
x=x.reshape((-1,2))
print(x)

[[2]
 [4]
 [6]
 [9]]
(4, 1)
2
[[2 4]
 [6 9]]


### Matrix and Tensors 

* Matrix is 2D array of scalars, denoted by scalars

* Tensors is an array with more than 2 axes ,denoted by X
    - think of Tensor as generalisation of an array with more than two axes

In [16]:
# here X is Matrix
X = np.array([[4,5,7],[10,11,13],[56,80,90]])
print(X)
print(X.shape)

[[ 4  5  7]
 [10 11 13]
 [56 80 90]]
(3, 3)


In [18]:
print(X[1][1])

11


In [20]:
X[1:,:] =2
print(X)

[[4 5 7]
 [2 2 2]
 [2 2 2]]


In [21]:
# here is T as Tensor
T = np.array([[[4,5,6],[3,6,7]],[[23,45,66],[45,78,87]]])
print(T.shape)

(2, 2, 3)


In [22]:
print(T)

[[[ 4  5  6]
  [ 3  6  7]]

 [[23 45 66]
  [45 78 87]]]


### Transponse

In [24]:
print(x)
xt = np.transpose(x)
print(xt)

[[2 4]
 [2 2]]
[[2 2]
 [4 2]]


### Broadcasting

In [28]:
l = np.array([[1,2,3,4],[4,9,7,6]])
print(l)
l = l+1
print(l)

[[1 2 3 4]
 [4 9 7 6]]
[[ 2  3  4  5]
 [ 5 10  8  7]]


In broadcasting we can do add,substract,square and square root

### Matrix Multiplication

In [31]:
x = np.array([[4,5,6],[10,11,12],[12,5,14]])
y = np.array([[4,5,6],[10,11,12],[12,5,14]]) 

In [32]:
prod = np.dot(x,y)
print(prod)

[[138 105 168]
 [294 231 360]
 [266 185 328]]


### Element wise Multiplication : Hadamard Product

In [33]:
x = np.array([[4,5,7],[10,11,14],[12,55,45]])
y=np.eye(3)
print(x)
print(y)

[[ 4  5  7]
 [10 11 14]
 [12 55 45]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
# element wise multiplication
print(x*y)

[[ 4.  0.  0.]
 [ 0. 11.  0.]
 [ 0.  0. 45.]]


### Norm

In [35]:
x= np.array([3,-2,5])
lp2 = np.linalg.norm(x)
print(lp2)

6.164414002968976


In [36]:
lp1=np.linalg.norm(x,ord=1)
print(lp1)

10.0


In [37]:
lpinf=np.linalg.norm(x,ord=np.inf)
print(lpinf)

5.0
