### Working with numpy- for mathematical operations

In [3]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
type(a)
print(a.shape)



[1 2 3 4 5]
(5,)


In [11]:
b=np.array([[1],[2],[3],[4],[5]])
print(b.shape)


(5, 1)


In [13]:
c=np.array([[1,2,3],[7,4,5]])
print(c.shape)
print(c[1][1])

(2, 3)
4


In [45]:
a=np.zeros((3,3))
print(a)
b=np.ones((3,3))
print(b)

#array of some constants
c=np.full((3,2),5)
print(c)

d=np.eye(4)
print(d)

#Random matrix
randomMatrix = np.random.random((2,3))
print(randomMatrix)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 5.  5.]
 [ 5.  5.]
 [ 5.  5.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 0.57737776  0.49124113  0.66704203]
 [ 0.94355233  0.75801427  0.61150539]]


In [26]:
#slicing
print(randomMatrix[ :,2 ])
randomMatrix[1,1:]=1
print(randomMatrix)

[ 0.92544647  0.34287468]
[[ 0.50291091  0.76172143  0.92544647]
 [ 0.281816    1.          1.        ]]


In [34]:
z=np.zeros((3,3),dtype = np.int64)
print(z)
z[1,:]=5
print(z)
z[:,-1]=7
print(z)


[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [5 5 5]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [35]:
#datatypes
print(type(z[1,1]))

<class 'numpy.int64'>


In [37]:
#mathematical operations
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

#Element wise addition
print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [39]:
print(np.sum(x))
print(np.sum(x,axis=1))

10
[3 7]


In [49]:
# stacking of arrays
print(a)
b=b**2
print(b)
a=np.stack((a,b),axis=0)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [55]:
#reshape Numpy array
#print(a)
#a=a.reshape(4,2)
a=np.arange(10)+5
print(a)


[ 5  6  7  8  9 10 11 12 13 14]


In [67]:
np.random.seed(1)
print(a)
np.random.shuffle(a)
print(a)

#this returns values from normal standard distribution
b=np.random.randn(2,3)
print(b)

c=np.random.randint(5,10,3)
print(c)

#if you want to pick one elemnet from array randomly
element=np.random.choice(a)
print(element)

[ 7 13  5  6 12 10  8  9 14 11]
[ 5 11  8 12  7  6 13  9 14 10]
[[ 1.5827523  -1.04514683  0.25759352]
 [-1.9593946  -1.50780766 -0.31529207]]
[7 9 6]
11


### Some Numpy method Statistics

In [ ]:
#min,max

In [8]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(np.min(a))
print(np.max(a))

#specify axis in the direction in case of multidmentional array
print(np.min(a,axis=0))
print(np.min(a,axis=1))


1
8
[1 2 3 4]
[1 5]


In [13]:
#mean - average of all the elements in the array
b=np.array([8,3,7,4,9])
m=sum(b)/5
print(m)
print(np.mean(b))
print(np.mean(a,axis=0))

6.2
6.2
[ 3.  4.  5.  6.]


In [14]:
#median - middle most value

c=np.array([2,5,4,8,0])
print(np.median(c))

4.0


In [16]:
#mean vs Average
# average is weighted

print(np.mean(c))


w = np.array([1,2,3,4,5])
print(np.average(c,weights=w))

3.8
3.73333333333


In [19]:
# standard deviation
u =np.mean(c)
mystd = np.sqrt(np.mean(abs(c-u)**2))
print(mystd)

#inbuilt function 
dev = np.std(c)
print(dev)

# Variance

print(mystd**2)
print(np.var(c))

2.71293199325
2.71293199325
7.36
7.36
